# Generated by Django 3.1.3 on 2020-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usual_day_start_morning', models.TimeField()),
                ('usual_day_start_afternoon', models.TimeField()),
                ('usual_day_end_morning', models.TimeField()),
                ('usual_day_end_afternoon', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
