# Generated by Django 3.1.3 on 2020-11-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
        ('shift', '0002_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber.service'),
        ),
    ]
