# Generated by Django 3.1.3 on 2020-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_shift_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='price',
            field=models.IntegerField(editable=False),
        ),
    ]
